
project:
  type: website

website:
  title: "Yuri Marca - Data Scientist"
  site-url: "https://yurimarca.github.io"
  description: "A personal website showcasing projects and studies posts."
  twitter-card: true
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog

    right:
      - icon: github
        href: https://github.com/yurimarca
      - icon: linkedin
        href: https://www.linkedin.com/in/yurimarca/

format:
  html:
    theme: flatly
    toc: true
