project:
  type: website

website:
  title: "Yuri Marca - Data Scientist"
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
    
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yurimarca
      - icon: linkedin
        href: https://lindekin.com/in/yurimarca
  page-footer: "2024 Yuri Marca"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



