
project:
  type: website

website:
  title: "My Portfolio and Blog"
  site-url: "https://yurimarca.github.io"
  description: "A personal website showcasing projects and blog posts."
  twitter-card: true
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/yurimarca
      - icon: linkedin
        href: https://www.linkedin.com/in/yourprofile/
  page-footer:
    left: "© 2024 Yuri Marca. All rights reserved."
    right: "Built with [Quarto](https://quarto.org/)."

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
