name: Render and Publish

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Cache TinyTeX
      - name: Cache TinyTeX
        uses: actions/cache@v3
        with:
          path: ~/.TinyTeX
          key: ${{ runner.os }}-tinytex
          restore-keys: |
            ${{ runner.os }}-tinytex

      # Set up Quarto
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      # Publish to GitHub Pages (and render)
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Always available in GitHub Actions

